# Generated by Django 5.1.4 on 2024-12-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_delete_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
        migrations.AddField(
            model_name='product',
            name='long_content',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='short_content',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
    ]
